apiVersion: v1
kind: Service
metadata:
  name: profile-communication
  labels:
    app: profile-communication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: profile-communication