server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, 
        - id: matching
          uri: http://localhost:8083
          predicates:
            - Path=/matches/**, 
        - id: profile-communication
          uri: http://localhost:8085
          predicates:
            - Path=/communications/**, 
        - id: security-privacy
          uri: http://localhost:8088
          predicates:
            - Path=/securities/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: http://userManagement:8080
          predicates:
            - Path=/users/**, 
        - id: matching
          uri: http://matching:8080
          predicates:
            - Path=/matches/**, 
        - id: profile-communication
          uri: http://profileCommunication:8080
          predicates:
            - Path=/communications/**, 
        - id: security-privacy
          uri: http://securityPrivacy:8080
          predicates:
            - Path=/securities/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
