---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  labels:
    app: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: username/user-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching
  labels:
    app: matching
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching
  template:
    metadata:
      labels:
        app: matching
    spec:
      containers:
        - name: matching
          image: username/matching:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-communication
  labels:
    app: profile-communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-communication
  template:
    metadata:
      labels:
        app: profile-communication
    spec:
      containers:
        - name: profile-communication
          image: username/profile-communication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-privacy
  labels:
    app: security-privacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-privacy
  template:
    metadata:
      labels:
        app: security-privacy
    spec:
      containers:
        - name: security-privacy
          image: username/security-privacy:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: user-management
  labels:
    app: user-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-management


---


apiVersion: v1
kind: Service
metadata:
  name: matching
  labels:
    app: matching
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: matching


---


apiVersion: v1
kind: Service
metadata:
  name: profile-communication
  labels:
    app: profile-communication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: profile-communication


---


apiVersion: v1
kind: Service
metadata:
  name: security-privacy
  labels:
    app: security-privacy
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: security-privacy

